<?php 
if ($this->element instanceof \Zend\Form\Element\Button) :
    echo $this->formElement($this->element);
elseif ($this->element instanceof \Zend\Form\Element\Radio) : ?>
    <div class="radio">
        <?php echo $this->formElement($this->element); ?>
    </div>
<?php elseif ($this->element instanceof \Zend\Form\Element\Text) : ?>
    <div class="form-group">
        <?php echo $this->formLabel($this->element); ?>
        <?php echo $this->formElement($this->element); ?>
    </div>
<?php elseif ($this->element instanceof \Zend\Form\Element) : ?>
    <div class="form-group">
        <?php echo $this->formElement($this->element); ?>
    </div>
<?php else :
    #error_log(get_class($this->element)); ?>
    <div class="form-group">
        <?php echo $this->formLabel($this->element); ?>
        <?php echo $this->formElement($this->element); ?>
        <?php echo $this->formElementErrors($this->element); ?>
    </div>
<?php endif;