<?php

$form->setAttribute('action', $this->url('blog-post', array('action' => 'create')))
      ->prepare();

echo $this->form()->openTag($form);

$blogPost = $form->get('blog-post');

echo $this->formRow($blogPost->get('title'));

echo $this->formCollection($blogPost->get('tags'));

echo $this->formHidden($form->get('csrf'));
echo $this->formElement($form->get('submit')); ?>

<?php echo $this->form()->closeTag();