<?php

$form->setAttribute('action', $this->url('debitor', array('action' => 'add')))
      ->prepare();

echo $this->form()->openTag($form);

$debitor = $form->get('debitor');

echo $this->formRow($debitor->get('business'));
echo $this->formRow($debitor->get('name'));
echo $this->formRow($debitor->get('handle'));
echo $this->formRow($debitor->get('default_rate'));
echo $this->formRow($debitor->get('payment_target'));
echo $this->formRow($debitor->get('turnus'));

echo $this->formCollection($debitor->get('contacts'));

echo $this->formHidden($form->get('csrf'));
echo $this->formElement($form->get('submit')); ?>

<?php echo $this->form()->closeTag();